### ISSUE TITLE
Error: References to elements of a temporary array expression

### ISSUE THREAD

**Issue by dehlen** [MartinLoeper/KVV-PHP-unofficial-#1]
Hello,

i am not really into php but I need this API for my new mobile application. What i did is: 
- install composer
- run composer install in directoy of composer.json ==> vendor folder was created
- added the files to my webspace
- created a test class like this:

```
<?php
require_once("vendor/autoload.php");

$efa = new \KVV\EFA();
$suggestions = $efa->autocomplete('Karlsruhe Durlach');
var_dump($suggestions);

?>
```

Unfortunately i get this error and can't figure out why: 

```
Fatal error: Cannot create references to elements of a temporary array expression in ...../kvvapi/src/EFA.php on line 128
```

You can see the folder structure on my webspace in the attached image.
![bildschirmfoto 2015-01-13 um 19 20 39](https://cloud.githubusercontent.com/assets/680180/5726108/14354d66-9b59-11e4-9ddc-581f88c57a48.png)

How can i get this library to work ? Thanks !

**Comment by MartinLoeper** [comment]
Hello,
You did everything right so far (referring to your code and screenshot).
What is your PHP's version number?
I developed and tested the code for PHP versions >=5.5 (as described in composer.json).
Althought some code might work in lower versions, <b>at least PHP 5.5</b> is required, because it enables function array dereferencing (http://php.net/manual/de/migration55.new-features.php#migration55.new-features.const-dereferencing).

Moreover I have to admit, that this project does not offer optimal runtime and memory consumption for hight-demanding mobile applications (this refers to the basic KVV API component, the KVV LIVE component is pretty fast!).
For this application area, there will be a Java based version in the near future (about 2 months), because I need this library for Android projects.

**Comment by dehlen** [comment]
I got version 5.4.35 running. The error happens for all lines with this format:

```
foreach($html('select#ix_origin option') AS &$station_origin) { //AS &$var creates error
}
```

Anything I can do about it ? Like i said i only use php because I have to. I am not a php expert. Thanks for getting in touch with me so quick !

EDIT: I changed my php version to 5.5 and It did work. Thanks !

**Comment by MartinLoeper** [comment]
If you have to use your PHP version, you have to replace all function array
dereferences.
I.e. remove the AND in "&$station_origin" -> "$station_origin".
This would be a workaround which unfortunately increases memory consumption.
Please let me know, if you get it to work.
